[package]
name = "duplicate-finder"
version = "0.1.0"
authors = ["Joinemm"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
twox-hash = "1.5.0"
structopt = "0.3"
